### ISSUE TITLE
Uncaught Error: Cannot find module './utilities/atom-utility'

### ISSUE THREAD

**Issue by balu-ertl** [BlueSilverCat/edit-numbers#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: [edit-numbers](https://github.com/BlueSilverCat/edit-numbers) package 0.3.0

### Stack Trace

Uncaught Error: Cannot find module './utilities/atom-utility'

```
At /usr/share/atom/resources/app/static/<embedded>:1

Error: Cannot find module './utilities/atom-utility'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/edit-numbers/lib/edit-numbers.js:7:29)
    at /packages/edit-numbers/lib/edit-numbers.js:461:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:57.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:57 editor:select-to-end-of-word (input.hidden-input)
     -0:56.2.0 core:select-right (input.hidden-input)
     -0:56 core:delete (input.hidden-input)
     -0:55.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:52 core:confirm (input.hidden-input)
     -0:50.9.0 core:select-all (input.hidden-input)
     -0:49 core:cut (input.hidden-input)
     -0:46.2.0 core:paste (input.hidden-input)
     -0:45.8.0 core:confirm (input.hidden-input)
     -0:42.1.0 core:paste (input.hidden-input)
     -0:41.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.2 
chrome-dark-syntax 0.7.0 
edit-numbers 0.3.0 
language-patch 1.2.0 
sort-lines 0.15.0 
Sublime-Style-Column-Selection 1.7.4 
wordcount 2.10.4 
```

**Comment by BlueSilverCat** [comment]
Thank you for your report.
I fix it.

This package was operated normally on my local environment.
But package installed from apm did not worked.
